spring.application.name=backend

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=time_heist
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=time_heist
spring.flyway.default-schema=time_heist
spring.flyway.create-schemas=true
spring.flyway.baseline-on-migrate=false
spring.flyway.repair-on-migrate=true

# Render provides PORT
server.port=${PORT:8080}

# Logging
logging.level.org.flywaydb=INFO
logging.level.org.hibernate=WARN
logging.level.org.springframework.orm.jpa=WARN

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

debug=false